### ISSUE TITLE
How to decrypt json ?

### ISSUE THREAD

**Issue by waraiotoko2501h** [NetNerd/8beatMap#7]
Thanks for the wonderful program.
I enjoy making chart with 8beatmap.

I understand it is not the right place to ask questions, but I want help.
I want to understand this program more.
I have been working on json decrypt for a long time.
But it has always failed.
what is [.c] file... all 512 byte.... Is this key ? ....xor decryption?
Some [.c] files content is same....
I would appreciate it if you could tell me about that.

**Comment by NetNerd** [comment]
I would like not to provide all details, because decrypting files allows changing many aspects of the game (including things that would allow cheating).

However, I can explain the purpose of ".c" files.

The content of ".c" (converted hexadecimal string to bytes) has been RSA encrypted using server-public-key.
After decryption it is an AES key for data in the corresponding json file.

**Comment by waraiotoko2501h** [comment]
Thanks for the quick answer.
That is useful information for me.
I will study RSA / AES.
It may take some time, but I'll try my best.

P.S.: I don't cheating it, I swear :) 
I will use only for my study.
